---
title: "Accomplishments"
---


#### [Oracle Certified Associate, Java SE 8 Programmer](files//eCertificate.pdf)

#### Crate a website Using R Markdown.

#### Student research Internship

St.Thomas University, Miami Gardens Florida. Summer 2015

- API (Access Protocols Interface), is a set of routines, protocols, and tools for building software applications. The API specifies how software components should interact and APIs are used when programming graphical user interface components. In this project, an API interface with Excel is constructed in order to access to weather information generated by the WeatherBug Network. By using the functions Webfunction and FilterXML from Excel along with the WeatherBug API Key, all of the following parameters are recorded: Outdoor Temperature, Humidity, Barometric Pressure, Light, Precipitation, Wet Bulb Temperature, Wind Speed, Wind Direction, Date, Time, Maximum Temperature, Minimum Temperature, Maximum Humidity, Minimum Humidity, Maximum Pressure, Minimum Pressure, and Gusts. Such access permits to create a database of spatial statistics from different weather stations that belong to the same network. The used protocol might be extended to other weather service providers as Weather Underground and the National Weather Service.

[poster](files//poster.pdf)


Shenzhen urban transport planning center, Beijing, China. Summer 2017

- Used python to analysis the bus traffic system. Including the bus transportation operating data and data for upload passengers.


#### Course work/Project

#### MAT-502 Statistical methods.

 - [HW3](files//MAT_502_HW3_Chen.html) | [HW4](files//MAT_502_HW4_Chen.html) | [Final Project](files//MAT_502_Final_Project_Chen.html)
 
#### MAT-602 Applied machine learning.

 - [HW1](files//MAT_602_HW1_chen.pdf) | [HW2](files//MAT_602_HW2_Chen.html) | [HW3](files//MAT_602_HW3_Chen.html) | [HW4](files//MAT_602_HW4_Chen.html) | [Final Project](files//MAT_602_Final_Project_Chen.html)

#### CIS-543 Program for data analytics.

 - [HW1](files//543_HW_1.html) | [HW4](files//543_HW_4.html) | [HW6](files//543_HW_6.html)
 
#### CIS-544 Data mining & machine learning.

 - [HW1](files//CIS_544_HW1_Chen.html) | [HW2](files//CIS_544_HW2_Chen.html) | [HW3](files//CIS_544_HW3_Chen.html) | [HW4](files//CIS_544_HW4_Chen.html) | [HW5](files//CIS_544_HW5_Chen.html) | [Final Project](files//CIS_544_Final_Project_Chen.pdf)
 
#### CIS-546 Data visualization.

  - [HW1](files//Austin_Animal_Center_Outcomes.nb.html) | [HW3](files/hw3.nb.html) | [Final Project](files//CIS-546_FINAL.nb.html)
  
#### CIS-547 Big Data Capstone

  - [Dynamic Tolls](files//Dynamic toll.html)
 
 
