---
title: "Education"
---
Florida International University (FIU), Miami FL.

Master of Science in Information Systems, Dec 2020

Curriculums:

- Project Management
  - [Microsoft project](files/ShipIT.pdf) 
- Database Management
  - Microsoft SQL Server Management Studio
  - [LucidChart](files/Product_Line.pdf)
- System Design & Analysis
  - JAVA - [Eclipse](https://github.com/sangavikk/SecondThoughtApp/tree/master/SecondThoughtApp/src/secondthoughtapp)
  - [Visual Paradigm](files/SecondThought.jpg)
  - GitHub
- Information Security Management
- Business Process Design
  - [LucidChart](files/bestbuy online purchasing.pdf)
- IS Strategy & Governance
- Data Warehousing
- E-Business and Blockchain Applications 
- Enterprise Information Systems
- Management of Information Systems Function


St.Thomas University (STU), Miami FL.

[Master of Science in Big Data Analytics](files/Master diploma.jpg), Aug 2018

Curriculums: 
 
- Fundamentals of Big Data Analytics
- Statistical Method
- Applied Machine Learning
- Data Mining and Machine Learning
- Programming for Big Data Analytics
- Data Visualization
- Big Data Warehousing
- Internet Protocols and Network Security
- Big Data Analytics Applications
- Big Data Analytics Capstone

St.Thomas University (STU), Miami FL.

[Bachelor of science in Computer Science](files/Bachelor diploma.jpg), May 2016

Curriculums:

- Microcomputer Applications
- C programming and Java programming
- Database concept 
- Web programming
- Computer Network & communication
- Linear algebra
- University physics
- ...
